server:
  port: 8080
  servlet:
    context-path: /backend

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://cznuxhxnbovtnl:dd74eefb923e1397a0c675c737585624ee4e0f56a3ba596db68642692ab15c93@ec2-3-215-57-87.compute-1.amazonaws.com:5432/d73us037k571sl
    username: cznuxhxnbovtnl
    password: dd74eefb923e1397a0c675c737585624ee4e0f56a3ba596db68642692ab15c93
  jpa:
    show-sql: true
    satabase-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para bootcamp DIO - Santander
  version: 1.0